AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamba_testframework

  Sample SAM Template for lamba_testframework
Globals:
  Function:
    Timeout: 180

Resources:
  UpdateInventory:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: UpdateInventory
      Description: This Lambda will update the Inventory
      Role: arn:aws:iam::754190025304:role/DBAccess
      CodeUri: Update_Inventory/
      Handler: update_inventory.lambdaHandler
      Runtime: nodejs14.x
      Events:
        InventoryAPI:
          Type: Api 
          Properties:
            Path: /update
            Method: post

Outputs:
  InventoryAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/iventory/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt UpdateInventory.Arn
